### ISSUE TITLE
Error with spfeas

### ISSUE THREAD

**Issue by bpstewar** [jgrss/spfeas#14]
When running spfeas, the log of completed features showed an error (included in attached image). I deleted the problematic line and ran the process again, but I would like to understand what caused this weird problem

![spfeas_logerror](https://user-images.githubusercontent.com/5446296/27879812-d433b152-6190-11e7-9ec2-28366cac9edb.PNG)

**Comment by jgrss** [comment]
@bpstewar have you received this error lately?

**Comment by bpstewar** [comment]
Nope, not in a while - actually, not at all in the last processing group. I am running some more stuff today, so I will let you know
