### ISSUE TITLE
Relative VRT paths

### ISSUE THREAD

**Issue by bpstewar** [jgrss/spfeas#18]
The output VRT files have absolute paths - could this be changed to relative?

**Comment by jgrss** [comment]
Yes, no problem. Would you want it as an option (absolute or relative)?

**Comment by bpstewar** [comment]
Personally, I would make it default, but I guess that is a matter of opinion. A flag would be more flexible, but there are already so many flags

**Comment by jgrss** [comment]
I have added this functionality and will be closing this issue. Please upgrade both SpFeas and MpGlue to see the changes.
