### ISSUE TITLE
Many vegetation indices cannot be computed

### ISSUE THREAD

**Issue by bouweandela** [jgrss/spfeas#21]
Many vegetation indices do not work, e.g. running the tool with `--triggers pndvi`.

**Comment by bpstewar** [comment]
Are you sure you are choosing the right source imagery using the --sensor flag?

**Comment by jgrss** [comment]
Good point @bpstewar. @bouweandela I haven't looked at this pull request yet, but can you confirm that the indices are broken when the correct sensor flag is chosen.

**Comment by bouweandela** [comment]
Yes
